#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Aaron Lou

# Short bio or description (displayed in the header)
description: Cornell '21 Math and CS

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/profile.jpg
  
#https://avatars1.githubusercontent.com/u/32228191?s=400&u=1929dbf7f1ad773d9f5b98c60a430a6feb50416f&v=4


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: About Me
    url: /
  - name: Blog
    url: /blog
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# Pagination
paginate: 5

# Includes an icon in the footer for each username you enter
footer-links:
  email: lou.aaron@yahoo.com
  facebook: wereawesome2
  github: daggertye
  linkedin: aaron-lou
  twitter: aaron_lou

# Text under the icons in footer
footer-text: Â© 2020 Aaron Lou

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: aaron-lou-com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-120354475-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://aaronlou.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /blog/:title/
paginate_path: /blog/page:num/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
